#version: '3.9'
services:
  springboot_3.3.2:
    image: ksngh/codeback
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "443:443"
    environment:
          SPRING_DATASOURCE_URL: jdbc:mariadb://codeback:3306/codeback
          SPRING_DATASOURCE_USERNAME: codeback
          SPRING_DATASOURCE_PASSWORD: ohboon
    depends_on:
      codeback:
        condition: service_healthy

  codeback:
    image: mariadb:11.4.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cocolabhub
      MYSQL_DATABASE: codeback
      MYSQL_USER: codeback
      MYSQL_PASSWORD: ohboon
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s