version: "3.8"

services:
  mariadb_11.4.2:
    image: mariadb:11.4.2
    environment:
      MYSQL_ROOT_PASSWORD: cocolabhub
      MYSQL_DATABASE: codeback
      MYSQL_USER: codeback
      MYSQL_PASSWORD: ohboon
    ports:
      - "3306:3306"

